/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Niloy_Banking_Management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Niloy Sarker
 */
public class PinChange extends javax.swing.JFrame {

    private final String accountNumber; // Assuming you have a variable to store the account number
    private final String pin;

    public PinChange(String accountNumber, String pin) {

        initComponents();
        this.accountNumber = accountNumber;
        this.pin = pin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Changebtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JPasswordField();
        t2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CHANGE YOUR PIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 290, 180, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("New PIN :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 340, 70, 20);

        Changebtn.setBackground(new java.awt.Color(0, 51, 102));
        Changebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Changebtn.setForeground(new java.awt.Color(255, 255, 255));
        Changebtn.setText("CHANGE");
        Changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Changebtn);
        Changebtn.setBounds(440, 420, 110, 25);

        BackBtn.setBackground(new java.awt.Color(0, 51, 102));
        BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("BACK");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(440, 450, 110, 25);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Re_Enter New PIN :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 370, 140, 20);

        t1.setBackground(new java.awt.Color(204, 255, 255));
        t1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(t1);
        t1.setBounds(360, 330, 170, 30);

        t2.setBackground(new java.awt.Color(204, 255, 255));
        t2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(t2);
        t2.setBounds(360, 370, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon("H:\\CSE\\Java Swing\\Project\\Banking_Management_System\\src\\Images\\atm.jpeg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -20, 900, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangebtnActionPerformed

        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/banking_mangement_system";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();

            String npin = t1.getText();
            String rpin = t2.getText();

            if (!npin.equals(rpin)) {
                JOptionPane.showMessageDialog(null, "Entered PIN does not match");
                return;
            }

            if (t1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter New PIN");
            } else if (t2.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Re-Enter new PIN");
            } else {
                
                
                String q1 = "update user_info set Pin = '" + rpin + "' where Pin = '" + pin + "' ";
                String q2 = "update bank set Pin = '" + rpin + "' where Pin = '" + pin + "' ";
                

                st.execute(q1);
                st.execute(q2);

                JOptionPane.showMessageDialog(null, "PIN changed successfully");

            }
        } catch (Exception e) {
            System.out.println("Error!" + e.getMessage());
        }
    }//GEN-LAST:event_ChangebtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        Tranjection tranjection = new Tranjection(accountNumber, pin);
        tranjection.setVisible(true);
        tranjection.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        tranjection.setTitle("NS Bank");
        tranjection.pack();
        tranjection.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton Changebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables
}
